---
title: "BUSAN516_Project"
author: "Sean Yen"
date: "3/5/2021"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Set up environment
rm(list = ls())
setwd("~/Documents/Rdata/BUSAN516/Project")

# Load data
hotels = read.csv("hotel_bookings.csv")
```

Explore data

```{r}
library(psych)
describe(hotels)
```

## Install Packages

```{r}
library(caTools)
library(rpart)
library(rpart.plot)
```

## Data Exploration

```{r}
hotel_type = hotels$hotel
length(unique(hotel_type))
```

```{r}
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

```

```{r}
getmode(hotels$arrival_date_week_number)
getmode(hotels$arrival_date_month)
```

## Training and Testing Data

```{r}
set.seed(1234)
split = sample.split(hotels$is_canceled, SplitRatio = 0.70)
HotelsTrain = subset(hotels, split==TRUE)
HotelsTest = subset(hotels, split==FALSE)
```

## Baseline Accuracy

```{r}
baseline_accuracy = sum(HotelsTest$is_canceled==FALSE)/nrow(HotelsTest)
baseline_accuracy
```

## Logistic Regression Model

```{r}
hotels.logit = glm(is_canceled ~ factor(hotel) + lead_time + adults +children + babies + factor(assigned_room_type) + booking_changes + factor(deposit_type) + factor(customer_type) + is_repeated_guest + previous_cancellations + previous_bookings_not_canceled+  factor(arrival_date_month) + arrival_date_day_of_month+ days_in_waiting_list + stays_in_weekend_nights
+ stays_in_week_nights + factor(meal) + arrival_date_year + arrival_date_week_number + country_group
+ required_car_parking_spaces + total_of_special_requests + adr
,  data = HotelsTrain, family=binomial)
summary(hotels.logit)

# Country and Market Segment are not included in this model
```

```{r}
library(coefplot)
coefplot(hotels.logit, innerCI=2, outerCI=0, intercept=FALSE, title="Logit Coefficient", decreasing=TRUE, color="turquoise",coefficients=c("lead_time","adults","children","factor(assigned_room_type)B","factor(assigned_room_type)C","factor(assigned_room_type)D","factor(assigned_room_type)E","factor(assigned_room_type)F","factor(assigned_room_type)G","factor(assigned_room_type)H","factor(assigned_room_type)I","factor(assigned_room_type)K","booking_changes","factor(deposit_type)Non Refund","factor(customer_type)Transient","factor(customer_type)Transient-Party","is_repeated_guest","previous_cancellations","previous_bookings_not_canceled","days_in_waiting_list","stays_in_weekend_nights","stays_in_week_nights","factor(meal)HB","factor(meal)SC","factor(meal)Undefined","arrival_date_year","total_of_special_requests","adr"))
```

## Model Predictions on test data

```{r}
HotelsTest$logit.pred = predict(hotels.logit, type="response", newdata = HotelsTest)
```

## Confusion matrix

```{r}
table(HotelsTest$is_canceled, HotelsTest$logit.pred > 0.5)
```

## Accuracy of the Logit model

```{r}
Logit_AIC = (20720+7811)/(20720+1830+5454+7811)
Logit_AIC
```

## CART

```{r}

hotels.cart = rpart(is_canceled ~ factor(hotel) + lead_time + adults +children + babies + factor(assigned_room_type) + booking_changes + factor(deposit_type) + factor(customer_type) + is_repeated_guest + previous_cancellations + previous_bookings_not_canceled+  factor(arrival_date_month) + arrival_date_week_number + arrival_date_day_of_month+ days_in_waiting_list
+ factor(arrival_date_year) + stays_in_weekend_nights
+ stays_in_week_nights + factor(meal) + factor(distribution_channel) + factor(reserved_room_type) + adr
+ required_car_parking_spaces + total_of_special_requests + factor(country_group), data = HotelsTrain, control = rpart.control(cp = 0.0055))
rpart.plot(hotels.cart)
```

```{r}
HotelsTest$cart.pred = predict(hotels.cart, HotelsTest)
```

## XGBoost

```{r}
library(xgboost)
col.full = c(1,3:13,16,18:25,28:32)
xgb.model <- xgboost(data = data.matrix(HotelsTrain[,col.full]), 
                  label = HotelsTrain[,2], 
                  eta = 0.1,
                  max_depth = 6, 
                  nround=100, 
                  subsample = 1,
                  colsample_bytree = 1,
                  num_class = 1,
                  min_child_weight = 5,
                  gamma = 5,
                  nthread = 30,
                  eval_metric = "logloss",
                  objective = "binary:logistic",
                  verbose = 0
                  )
HotelsTest$xgb.pred <- predict(xgb.model, data.matrix(HotelsTest[,col.full]))
```

## Model Evaluations using AUC method

```{r}
# Load pROC
library(pROC)

# Calculate AUC of logistic regression model
auc.logit = roc(HotelsTest$is_canceled, HotelsTest$logit.pred)
auc(auc.logit)
auc_curve.logit <- plot.roc(HotelsTest$is_canceled, HotelsTest$logit.pred, main = "ROC curve Logit Prediction", percent=TRUE, cex.main=0.75, cex.lab = 0.75)

# Calculate AUC of CART model
auc.cart = roc(HotelsTest$is_canceled, HotelsTest$cart.pred)
auc(auc.cart)
auc_curve.cart <- plot.roc(HotelsTest$is_canceled, HotelsTest$cart.pred, main = "ROC curve CART Prediction", percent=TRUE, cex.main=0.75, cex.lab = 0.75)

# Calculate AUC of XGBoost model
auc.xgb = roc(HotelsTest$is_canceled, HotelsTest$xgb.pred)
auc(auc.xgb)
auc_curve.xgb <- plot.roc(HotelsTest$is_canceled, HotelsTest$xgb.pred, main = "ROC curve XGBoost Prediction", percent=TRUE, cex.main=0.75, cex.lab = 0.75)
```

```{r}
colAUC(X = cbind(Logit = HotelsTest$logit.pred, CART = HotelsTest$cart.pred, XGB = HotelsTest$xgb.pred), HotelsTest$is_canceled, plotROC = TRUE)
```

## Model Evaluations using AIC method

```{r}
table(HotelsTest$is_canceled, HotelsTest$cart.pred > 0.5)
table(HotelsTest$is_canceled, HotelsTest$xgb.pred > 0.5)
```

```{r}
# CART AIC
cart_AIC = (20405+8377)/(20405+2145+4890+8377)
cart_AIC

# XGBoost AIC
xgb_AIC = (20758+9766)/(20758+1792+3501+9766)
xgb_AIC
```

| Model   | Baseline | Logit  | CART   | XGBoost |
|---------|----------|--------|--------|---------|
| **AIC** | 62.96%   | 79.66% | 80.36% | 85.22%  |
| AUC     | \-       | 84.16% | 85.41% | 92.79%  |

# XG Boost Visualization

```{r}
importance_matrix = xgb.importance(model = xgb.model)
# xgb.plot.importance(importance_matrix,top_n = 10, rel_to_first = TRUE, xlab = "Relative importance")
library(Ckmeans.1d.dp)
xgb.ggplot.importance(importance_matrix, rel_to_first = TRUE, xlab = "Relative importance")
```

```{r}
# write.csv(HotelsTest, file = "BUSAN516_Project_ModelResults.csv")
```
